# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.define :slave do |slave_config|
    slave_config.vm.customize ["modifyvm", :id, "--name", "Hadoop Slave", "--memory", 1024]
    slave_config.vm.box = "base-hadoop"
    #slave_config.vm.forward_port 90, 9090
    slave_config.vm.network :hostonly, "10.10.10.51"
    #slave_config.vm.provision :puppet
	slave_config.ssh.forward_agent = true
  end
  config.vm.define :master do |master_config|
    master_config.vm.customize ["modifyvm", :id, "--name", "Hadoop Master", "--memory", 1024]
    master_config.vm.box = "base-hadoop"
    #master_config.vm.forward_port 80, 8080
    master_config.vm.network :hostonly, "10.10.10.50"
    #master_config.vm.provision :puppet
    master_config.ssh.forward_agent = true
    #master_config.vm.provision :shell, :path => "hadoop_start.sh"
  end
end